### ISSUE TITLE
sincos 

### ISSUE THREAD

**Issue by sand0u** [luxuia/dxbc_reader#10]
The sincos command seems to be converted incorrectly
sincos r1.x r2.x r3.x need to be  r1.x = sin(r3.x); r2.x = cos(r3.x), but dxbc_reader result to r1.x = sin(r2.x); r1.x = cons(r3.x);

**Comment by luxuia** [comment]
sincos r1.x r2.x r3.x need to be r2.x = sin(r1.x); r3.x = cos(r1.x)
